export const standardReviewForms = [
  {
    title: "Standard Form",
    description:
      "This is a standard form for review which help you collect name, email, rating, and feedback.",
    isActive: true,
    isStandard: true,
    fields: [
      {
        label: "Name",
        placeholder: "Enter your name",
        type: "text",
        name: "name",
        isActive: true,
        shouldDisabled: false,
      },
      {
        label: "Email",
        placeholder: "Enter your email",
        type: "email",
        name: "email",
        isActive: true,
        shouldDisabled: false,
      },
      {
        label: "Rating",
        type: "rating",
        name: "rating",
        isActive: true,
        shouldDisabled: false,
        min: 1,
        max: 5,
      },
      {
        label: "Feedback",
        placeholder: "Enter your feedback",
        type: "textarea",
        name: "feedback",
        isActive: true,
        shouldDisabled: false,
      },
    ],
  },
  {
    title: "Hotel Review Form",
    description:
      "This is a hotel review form which help you collect guest name, email, room number, rating, and feedback.",
    isActive: true,
    isStandard: true,
    fields: [
      {
        label: "Guest Name",
        placeholder: "Enter guest name",
        type: "text",
        name: "name",
        isActive: true,
        shouldDisabled: false,
      },
      {
        label: "Email",
        placeholder: "Enter your email",
        type: "email",
        name: "email",
        isActive: true,
        shouldDisabled: false,
      },
      {
        label: "Room Number",
        placeholder: "Enter room number",
        type: "text",
        name: "roomNumber",
        isActive: true,
        shouldDisabled: false,
      },
      {
        label: "Rating",
        type: "rating",
        name: "rating",
        isActive: true,
        shouldDisabled: false,
        min: 1,
        max: 5,
      },
      {
        label: "Feedback",
        placeholder: "Enter your feedback",
        type: "textarea",
        name: "feedback",
        isActive: true,
        shouldDisabled: false,
      },
    ],
  },
];
